### ISSUE TITLE
brew installation fails : -e:276:in `<main>': undefined method `odie' for main:Object (NoMethodError)

### ISSUE THREAD

**Issue by sebma** [Linuxbrew/install#24]
# Please always follow these steps:
To help us debug your issue please explain:
- What you were trying to do (and why)
Trying to install Linuxbrew
- What happened (include command output)
```
id: cannot find name for group ID 1234567
./install:276:in `<main>': undefined method `odie' for main:Object (NoMethodError)
```

- What you expected to happen
A proper installation
- Step-by-step reproduction instructions : 
```
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"
==> Select the Linuxbrew installation directory
- Enter your password to install to /home/linuxbrew/.linuxbrew (recommended)
- Press Control-D to install to /users/EtuY/1234567/.linuxbrew
- Press Control-C to cancel installation

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for 1234567: 
==> This script will install:
/users/EtuY/1234567/.linuxbrew/bin/brew
/users/EtuY/1234567/.linuxbrew/share/doc/homebrew
/users/EtuY/1234567/.linuxbrew/share/man/man1/brew.1
/users/EtuY/1234567/.linuxbrew/share/zsh/site-functions/_brew
/users/EtuY/1234567/.linuxbrew/etc/bash_completion.d/brew
/users/EtuY/1234567/.cache/Homebrew/
/users/EtuY/1234567/.linuxbrew/Homebrew
id: cannot find name for group ID 1234567
-e:276:in `<main>': undefined method `odie' for main:Object (NoMethodError)
```

On our university workstations, my homedir is on NFS and the user management used is LDAP.

BTW : `id -gn` shows : 
```
$ id -gn
id: cannot find name for group ID 1234567
1234567
$ echo $?
1
```

Can you help ?

**Comment by sjackman** [comment]
```
id: cannot find name for group ID 1234567
```
That's not good and may create trouble for you going forward. Is that `/usr/bin/id`? Please report
```sh
which -a id
/usr/bin/id -gn
```

**Comment by sebma** [comment]
```
$ which -a id
/usr/bin/id
```

I believe there's something wrong with their LDAP configuration.

**Comment by sjackman** [comment]
I've opened PR https://github.com/Linuxbrew/install/pull/25 to address `undefined method odie`

**Comment by sjackman** [comment]
> I believe there's something wrong with their LDAP configuration.

I'd suggest opening a ticket with your support team.

In the mean time, you can try downloading the `install` script commenting out this line:
https://github.com/Linuxbrew/install/blob/220647fbd8d4b926567ad257b6cc4ea187402d19/install#L276

**Comment by sjackman** [comment]
Fixed by PR https://github.com/Linuxbrew/install/pull/25

**Comment by sebma** [comment]
Thanks :-)

**Comment by sjackman** [comment]
Thanks for the bug report!
