### ISSUE TITLE
Fedora requires rubygem-json package before Linuxbrew installation

### ISSUE THREAD

**Issue by duvrai** [Linuxbrew/install#26]
While trying to install Linuxbrew on Fedora 27 i got

    /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- json (LoadError)

In Linuxbrew/brew#447 I discovered that I had to install `rubygem-json` on Fedora before trying to install Linuxbrew:

    sudo dnf install rubygem-json

It would be nice
- to find this requirement or some more generic explanation in the installation instructions on http://linuxbrew.sh/
- to get instructions when the installation fails because of this

**Comment by sjackman** [comment]
Thanks for the bug report, Duvrai. Does `export HOMEBREW_FORCE_VENDOR_RUBY=1` work around this issue for you?

**Comment by sjackman** [comment]
I see that I've run into this issue myself with the `fedora` Docker image. See https://github.com/Linuxbrew/docker/blob/master/fedora/Dockerfile#L5

**Comment by duvrai** [comment]
> Does export HOMEBREW_FORCE_VENDOR_RUBY=1 work around this issue for you?

Yes it did, after uninstalling `rubygem-json` from Fedora, I set `HOMEBREW_FORCE_VENDOR_RUBY=1`. When I ran brew after that, it went fetching `portable-ruby-2.3.3.x86_64_linux.bottle.1.tar.gz`. Brew seems to run fine now without `rubygem-json`.

**Comment by sjackman** [comment]
Glad to hear that workaround works for you.
