### ISSUE TITLE
Should curl be used from $PATH when installing linuxbrew?

### ISSUE THREAD

**Issue by sjackman** [Linuxbrew/install#27]
_From @Gwang-Jin on May 16, 2018 2:4_

Hello. When I started linuxbrew with non-root user, I met a problem with curl path.
In my system,
`/usr/bin/curl --version `

`curl 7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.12.9.0 zlib/1.2.3 libidn/1.18 libssh2/1.2.2
Protocols: tftp ftp telnet dict ldap ldaps http file https ftps scp sftp 
Features: GSS-Negotiate IDN IPv6 Largefile NTLM SSL libz`

, and the version of curl is too old to install linuxbrew.

So I compiled curl source in my /home/my/local. But when installing linuxbrew, the script of
`https://raw.githubusercontent.com/Linuxbrew/install/master/install`
always use `/usr/bin/curl` although there is another curl in $PATH `/home/my/local/bin/curl`

Could you change `install`  into
`386     system "/bin/bash -o pipefail -c 'curl -#{curl_flags} #{BREW_REPO}/tarball/master | /bin/tar xz -m --strip 1'"`

`392       system "/bin/bash -o pipefail -c 'curl -#{curl_flags} #{CORE_TAP_REPO}/tarball/master | /bin/tar xz -m --strip 1'"`
?

Then we can use curl from $PATH.

_Copied from original issue: Linuxbrew/homebrew-core#7694_

**Comment by sjackman** [comment]
_From @iMichka on May 17, 2018 20:9_

Hi. I think it would be fine to make that change (replacing `/usr/bin/curl` with `curl`). I think this comes from the mac logic where they may want to force you to use the system's curl. On Linux it is probably fine to use whatever curl is in the path (but maybe upstream would be interested to make that change too).

@sjackman Any opinion on this. I bet it has already been discussed :)

By the way, this issue should have been raison on a different issue tracker:
https://github.com/Linuxbrew/install

We can continue the discussion here for the moment though.

**Comment by sjackman** [comment]
I'm fine with using `curl` from the `PATH`. Now that GitHub has killed off old SSL protocols, it's becoming more common that the host's `/usr/bin/curl` is not sufficient to install Linuxbrew.

@Gwang-Jin Would you like to open a PR to fix it?
https://github.com/Linuxbrew/install/blob/04a18ba610d087d8b3a0662ad65f18d7361ae85d/install#L386

**Comment by Gwang-Jin** [comment]
Yes. But I am not familiar with GitHub.

**Comment by iMichka** [comment]
We can guide you through the process. This change is quite small, so you do it directly from the GitHub website.

Go to this page https://github.com/Linuxbrew/install/blob/master/install. There you will be able to edit the code directly. You can follow this 8 step instructions to get this done https://help.github.com/articles/editing-files-in-your-repository/

**Comment by Gwang-Jin** [comment]
OK. I will.

**Comment by maxim-belkin** [comment]
And it's done! Thank you, @Gwang-Jin! 🎉

**Comment by waldyrious** [comment]
> And it's done! Thank you, `@Gwang-Jin`! :tada:

For future reference, the relevant PR is #28.
