### ISSUE TITLE
Created ~/.cache directory is owned by root

### ISSUE THREAD

**Issue by yukihane** [Linuxbrew/install#30]
Installer works:
```
==> /usr/bin/sudo /bin/mkdir -p /home/myname/.cache/Homebrew
==> /usr/bin/sudo /bin/chmod g+rwx /home/myname/.cache/Homebrew
==> /usr/bin/sudo /bin/chown myname /home/myname/.cache/Homebrew
==> /usr/bin/sudo /bin/chgrp myname /home/myname/.cache/Homebrew
```
So if .cache does not exist, root creates it without chown/chgrp.

**Comment by sjackman** [comment]
Good catch. Thanks for the bug report, @yukihane . Would you like to open a PR to fix the issue?
See this line:
https://github.com/Linuxbrew/install/blob/ed60e76702a780b4a4cde04f49ef9f41d64abbc3/install#L323
You could add `File.dirname(HOMEBREW_CACHE)` to this list.

**Comment by sjackman** [comment]
This repository is deprecated. It has been merged into Homebrew/install.
