### ISSUE TITLE
Uninstall script deletes system files if run with sudo

### ISSUE THREAD

**Issue by f14h** [Linuxbrew/install#31]
Uninstalling using `/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/uninstall)"`  results in
> rmdir: couldn't delete '/home/user/.linuxbrew': The folder is not empty
> Warning: Failed during: /usr/bin/sudo rmdir /home/user/.linuxbrew
> Warning: Homebrew partially uninstalled (but there were steps that failed)!
> To finish uninstalling rerun this script with `sudo`.
> The following possible Homebrew files were not deleted:
> /home/user/.linuxbrew/.circleci/
> /home/user/.linuxbrew/share/
> /home/user/.linuxbrew/_config.yml
> /home/user/.linuxbrew/var/
> /home/user/.linuxbrew/lib/
> /home/user/.linuxbrew/etc/
> You may wish to remove them yourself.

Running the file with sudo results in 
a)
> Don't run this as root!
> Warning: This script will remove:
> /usr/bin/brew -> /usr/bin/linuxbrew

b)
> ==> /usr/bin/sudo /usr/bin/find /usr/bin /usr/include /usr/lib /usr/sbin /usr/share -name .DS_Store -delete
> ==> /usr/bin/sudo /usr/bin/find /usr/bin /usr/include /usr/lib /usr/sbin /usr/share -depth -type d -empty -exec rmdir {} ;
> ==> /usr/bin/sudo rmdir /usr

Potentially removing system folders and files. The script looks to me inconsistent first suggesting rerunning it with root and then warning not to run it with root. Why is sudo needed anyway, if the whole installation takes place in the homedir?

**Comment by sjackman** [comment]
> To finish uninstalling rerun this script with sudo.

The Linuxbrew `uninstall` script should not make this recommendation. Would you like to open a PR to prevent it doing so?

**Comment by f14h** [comment]
Thank you for your answer. Could you clarify what you mean with PR? I just wanted to report the issue, don't have the knowledge to fix it myself. Thank you! 
Edit: Maybe fix the script so it doesn't suggest it and confirms if you really want to run it with sudo.

**Comment by sjackman** [comment]
I was suggesting that you open a pull request (PR) to remove this suggestion.
Click this line to edit the `uninstall` file
https://github.com/Linuxbrew/install/edit/master/uninstall#L311
and then delete this line
https://github.com/Linuxbrew/install/blob/9f382bfd55b6a782dfcb6d8d98ed27535c4f9d93/uninstall#L311
then scroll down, type a comment, and select `Propose file chage`

**Comment by sjackman** [comment]
Fixed by #32
