### ISSUE TITLE
Fails when running user has restrictive umask

### ISSUE THREAD

**Issue by athas** [Linuxbrew/install#33]
I use a restrictive umask by default:

```
$ umask
0077
```

Unfortunately, this umask is inherited by the installation script when it creates the `/home/linuxbrew` directory, and it means my normal user cannot read it, so installation fails.  I recommend that the script should manually set the desired permissions on the created `/home/linuxbrew` directory.

**Comment by maxim-belkin** [comment]
great suggestion! Would you be willing to submit a PR?

**Comment by athas** [comment]
I might give it a shot, but I'm not much familiar with Ruby.  One solution might be to simply `umask 022` in `install.sh`.  Does the installation script write anywhere but `/home/linuxbrew`?

**Comment by sjackman** [comment]
Fixed by PR https://github.com/Linuxbrew/install/pull/34. Thanks, Troels!
