### ISSUE TITLE
Ruby install script fails on Raspberry Pie 2 raspbian

### ISSUE THREAD

**Issue by dwoodgate** [Linuxbrew/install#41]
I believe the ruby-installer is failing because there is no 2.3.7 ruby matching the architecture tag armv7l_linux on the bintray site. 

Maybe if uname -m returns armv7l, force it to armv6? (unsure if there's actually a difference)

```
pi@retropie:~ $ sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
==> Installing Ruby to /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    33    0    33    0     0     62      0 --:--:-- --:--:-- --:--:--    62

gzip: stdin: not in gzip format

```
See also this comment.
https://github.com/Linuxbrew/brew/issues/855#issuecomment-426145974

**install-ruby**
```
tag=`uname -m`_`uname -s | tr A-Z a-z`

echo >&2 "==> Installing Ruby to $prefix"
mkdir -p $prefix
curl -L https://homebrew.bintray.com/bottles-portable-ruby/portable-ruby-$version.$tag.bottle.tar.gz \
	| tar -xz -C $prefix
```
Uname
```
pi@retropie:~ $ echo `uname -m`_`uname -s | tr A-Z a-z`
armv7l_linux
pi@retropie:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
```

**Comment by sjackman** [comment]
Yes, this is a bug in `install`. It should use code like this in `cmd/vendor-install` which allows both `armv6` and `armv7`.
https://github.com/Linuxbrew/brew/blob/c848038f0ead14fcc3b50098609c7322c727d0d3/Library/Homebrew/cmd/vendor-install.sh#L28

Are you interested in submitting a pull request to fix `install`?
https://github.com/Linuxbrew/install/blob/43a0177266a875e5087adba64d6fa577c4cd7e56/install-ruby#L12

**Comment by sjackman** [comment]
This repository is deprecated. It has been merged into Homebrew/install.
