### ISSUE TITLE
Cannot uninstall linuxbrew

### ISSUE THREAD

**Issue by AgentEric** [Linuxbrew/install#42]
The command line:

> /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/uninstall)"

output: /usr/bin/ruby: no such file or directory

My OS is :manjaro
linuxbrew directory: /home/linuxbrew 
Didn't install anything via linuxbrew.
Should I just "rm -rf /home/linuxbrew"？worried about that， so come here to create an issue.

**Comment by sjackman** [comment]
Try…
`/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/uninstall)"`
or if that fails
```sh
rm -rf /home/linuxbrew
```
is just fine.
