### ISSUE TITLE
Handle systems with old curl versions

### ISSUE THREAD

**Issue by waldyrious** [Linuxbrew/install#56]
I'm facing some installation issues that could perhaps be handled more seamlessly by the installer script. The system is a CentOS 6 machine where I have no sudo access.

The installation command
```
sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
```

uses the system `curl`, and the initial download works; However, the actual installation script fails with
```
...
==> Downloading and installing Linuxbrew...
error: SSL connect error while accessing https://github.com/Homebrew/brew/info/refs
fatal: HTTP request failed
Failed during: git fetch origin master:refs/remotes/origin/master --tags --force
```

This seems to be due to git using the system curl and failing to access the secure URL.

After some investigation, I found a reference to `GIT_CURL_VERBOSE` in the [git documentation](https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables#_networking), which allowed me to see more details about what's failing:

<details>

```
$ GIT_CURL_VERBOSE=1 sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
==> This script will install:
/home/waldyrious/.linuxbrew/bin/brew
/home/waldyrious/.linuxbrew/share/doc/homebrew
/home/waldyrious/.linuxbrew/share/man/man1/brew.1
/home/waldyrious/.linuxbrew/share/zsh/site-functions/_brew
/home/waldyrious/.linuxbrew/etc/bash_completion.d/brew
/home/waldyrious/.cache/Homebrew/
/home/waldyrious/.linuxbrew/Homebrew

Press RETURN to continue or any other key to abort
==> Downloading and installing Linuxbrew...
* Couldn't find host github.com in the .netrc file; using defaults
* About to connect() to github.com port 443 (#0)
*   Trying 140.82.118.4... * Connected to github.com (140.82.118.4) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* NSS error -12190
* Error in TLS handshake, trying SSLv3...
> GET /Homebrew/brew/info/refs?service=git-upload-pack HTTP/1.1
User-Agent: git/1.7.11.4
Host: github.com
Accept: */*
Pragma: no-cache

* Connection died, retrying a fresh connect
* Expire cleared
* Closing connection #0
* Issue another request to this URL: 'https://github.com/Homebrew/brew/info/refs?service=git-upload-pack'
* Couldn't find host github.com in the .netrc file; using defaults
* About to connect() to github.com port 443 (#0)
*   Trying 140.82.118.4... * Connected to github.com (140.82.118.4) port 443 (#0)
* TLS disabled due to previous handshake failure
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* NSS error -12286
* Expire cleared
* Closing connection #0
* Couldn't find host github.com in the .netrc file; using defaults
* About to connect() to github.com port 443 (#0)
*   Trying 140.82.118.4... * Connected to github.com (140.82.118.4) port 443 (#0)
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* NSS error -12190
* Error in TLS handshake, trying SSLv3...
> GET /Homebrew/brew/info/refs HTTP/1.1
User-Agent: git/1.7.11.4
Host: github.com
Accept: */*
Pragma: no-cache

* Connection died, retrying a fresh connect
* Expire cleared
* Closing connection #0
* Issue another request to this URL: 'https://github.com/Homebrew/brew/info/refs'
* Couldn't find host github.com in the .netrc file; using defaults
* About to connect() to github.com port 443 (#0)
*   Trying 140.82.118.4... * Connected to github.com (140.82.118.4) port 443 (#0)
* TLS disabled due to previous handshake failure
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* NSS error -12286
* Expire cleared
* Closing connection #0
error: SSL connect error while accessing https://github.com/Homebrew/brew/info/refs
fatal: HTTP request failed
Failed during: git fetch origin master:refs/remotes/origin/master --tags --force
```
</details>

I'm wondering if there could be a way for the install script to automatically detect and avoid this issue, or at least check for the minimum versions of `curl` and `git` and exit with a clear error instead of starting the install only to fail later on. Of course, I'd prefer the first option if possible. I'd be happy to submit a PR if I can get either approach to work, but I need some guidance.

**Comment by sjackman** [comment]
The simplest work around is to somehow get a recent copy of OpenSSL and curl on your system, probably by compiling them from source, and then putting that updated `curl` in your `PATH` before running the Linuxbrew installer.

Yes, it'd be good for the installer to print an error message and exit if curl is too old. Would you like to open a PR to do that?

**Comment by waldyrious** [comment]
> The simplest work around is to somehow get a recent copy of OpenSSL and curl on your system, probably by compiling them from source, and then putting that updated curl in your PATH before running the Linuxbrew installer.

I actually do have a more recent curl from my previous round of (ultimately unsuccessful) experiments from about a year ago; I had compiled it using pkgsrc:

```
$ export PATH=$HOME/.pkgsrc/bin:$PATH
$ which curl -a
~/.pkgsrc/bin/curl
/usr/bin/curl
$ /usr/bin/curl --version
curl 7.19.7 ...
$ ~/.pkgsrc/bin/curl --version
curl 7.58.0 ... Release-Date: 2018-01-24
```

But it still doesn't seem to work:

```
$ sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

If I [set curl and git to use insecure connections](https://github.com/Linuxbrew/brew/wiki/FAQ#why-does-curl-fail), I get further ahead, but then it fails when installing Ruby:

<details>

```
$ echo insecure >> ~/.curlrc
$ git config --global http.sslVerify false
$ HOMEBREW_CURLRC=1 GIT_CURL_VERBOSE=1 sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
==> This script will install:
/home/waldyrious/.linuxbrew/bin/brew
/home/waldyrious/.linuxbrew/share/doc/homebrew
/home/waldyrious/.linuxbrew/share/man/man1/brew.1
/home/waldyrious/.linuxbrew/share/zsh/site-functions/_brew
/home/waldyrious/.linuxbrew/etc/bash_completion.d/brew
/home/waldyrious/.cache/Homebrew/
/home/waldyrious/.linuxbrew/Homebrew

Press RETURN to continue or any other key to abort
==> Downloading and installing Linuxbrew...
* Couldn't find host github.com in the .netrc file; using defaults
*   Trying 140.82.118.4...
* TCP_NODELAY set
* Connected to github.com (140.82.118.4) port 443 (#0)
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* Server certificate:
*  subject: businessCategory=Private Organization; 1.3.6.1.4.1.311.60.2.1.3=US; 1.3.6.1.4.1.311.60.2.1.2=Delaware; serialNumber=5157550; C=US; ST=California; L=San Francisco; O=GitHub, Inc.; CN=github.com
*  start date: May  8 00:00:00 2018 GMT
*  expire date: Jun  3 12:00:00 2020 GMT
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert SHA2 Extended Validation Server CA
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
> GET /Homebrew/brew/info/refs?service=git-upload-pack HTTP/1.1
Host: github.com
User-Agent: git/2.16.1
Accept: */*
Accept-Encoding: gzip
Accept-Language: en-US, *;q=0.9
Pragma: no-cache

< HTTP/1.1 200 OK
< Server: GitHub Babel 2.0
< Content-Type: application/x-git-upload-pack-advertisement
< Transfer-Encoding: chunked
< Expires: Fri, 01 Jan 1980 00:00:00 GMT
< Pragma: no-cache
< Cache-Control: no-cache, max-age=0, must-revalidate
< Vary: Accept-Encoding
< X-Frame-Options: DENY
< X-GitHub-Request-Id: 99C1:3D20E:EEDDEF:165FE7D:5CA544BA
< 
* Connection #0 to host github.com left intact
* Couldn't find host github.com in the .netrc file; using defaults
* Found bundle for host github.com: 0xe082c0 [can pipeline]
* Re-using existing connection! (#0) with host github.com
* Connected to github.com (140.82.118.4) port 443 (#0)
> POST /Homebrew/brew/git-upload-pack HTTP/1.1
Host: github.com
User-Agent: git/2.16.1
Accept-Encoding: gzip
Content-Type: application/x-git-upload-pack-request
Accept: application/x-git-upload-pack-result
Content-Encoding: gzip
Content-Length: 3187

* upload completely sent off: 3187 out of 3187 bytes
< HTTP/1.1 200 OK
< Server: GitHub Babel 2.0
< Content-Type: application/x-git-upload-pack-result
< Transfer-Encoding: chunked
< Expires: Fri, 01 Jan 1980 00:00:00 GMT
< Pragma: no-cache
< Cache-Control: no-cache, max-age=0, must-revalidate
< Vary: Accept-Encoding
< X-Frame-Options: DENY
< X-GitHub-Request-Id: 99C1:3D20E:EEDE35:165FEE5:5CA544BA
< 
remote: Enumerating objects: 121066, done.
* Connection #0 to host github.com left intact MiB | 8.25 MiB/s   
remote: Total 121066 (delta 0), reused 0 (delta 0), pack-reused 121066
Receiving objects: 100% (121066/121066), 28.65 MiB | 8.33 MiB/s, done.
Resolving deltas: 100% (88545/88545), done.
From https://github.com/Homebrew/brew
 * [new branch]          master     -> origin/master
 * [new tag]             0.1        -> 0.1
 ...SNIP...
 * [new tag]             2.0.6      -> 2.0.6
Checking out files: 100% (1742/1742), done.
HEAD is now at 8ce7b1d39 Merge pull request #5958 from xu-cheng/compiler
/usr/bin/ruby: no such file to load -- rubygems (LoadError)
==> Downloading https://linuxbrew.bintray.com/bottles-portable-ruby/portable-ruby-2.3.7.x86_64_linux.bottle.tar.gz
curl: (35) SSL connect error
==> Downloading https://github.com/Homebrew/homebrew-portable-ruby/releases/download/2.3.7/portable-ruby-2.3.7.x86_64_linux.bottle.tar.gz

curl: (35) SSL connect error
Error: Failed to download https://linuxbrew.bintray.com/bottles-portable-ruby/portable-ruby-2.3.7.x86_64_linux.bottle.tar.gz and https://github.com/Homebrew/homebrew-portable-ruby/releases/download/2.3.7/portable-ruby-2.3.7.x86_64_linux.bottle.tar.gz!

Do not file an issue on GitHub about this: you will need to figure out for
yourself what issue with your internet connection restricts your access to
both Bintray (used for Homebrew bottles/binary packages) and GitHub
(used for Homebrew updates).
Error: Failed to install vendor Ruby.
Error: Git must be installed and in your PATH!
Failed during: /home/waldyrious/.linuxbrew/bin/brew update --force
```
</details>

Perhaps the solution used in #27 needs to be applied elsewhere as well?

**Comment by waldyrious** [comment]
> Yes, it'd be good for the installer to print an error message and exit if curl is too old. Would you like to open a PR to do that?

Yes, I would. Is there any existing code I could use as reference for the required changes? Or otherwise, where do you suggest I should start looking at?

**Comment by sjackman** [comment]
You also need to download an updated copy of `cacert.pem` and put it somewhere that OpenSSL and curl can find it.
See https://curl.haxx.se/docs/caextract.html
and https://github.com/Homebrew/linuxbrew-core/blob/842e313db920c2d505147c0c57cfdde60087013d/Formula/openssl.rb#L26

Once `curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh` succeeds you'll be able to make progress.

**Comment by sjackman** [comment]
>> Yes, it'd be good for the installer to print an error message and exit if curl is too old. Would you like to open a PR to do that?

> Yes, I would. Is there any existing code I could use as reference for the required changes? Or otherwise, where do you suggest I should start looking at?

Now that I think about it, if `curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh` fails our installer won't even be run, so there's not much we can do, other than update the FAQ and possible the install instructions.

**Comment by waldyrious** [comment]
> Once `curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh` succeeds you'll be able to make progress.

> if `curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh` fails our installer won't even be run

That's the thing -- the initial download works without issues, when using the system curl (v7.19.7); the failures I had been getting (and which prompted me to open this issue) only happen once the installer is running, as the logs included in the opening comment show.

The failure mentioned in the [other comment](https://github.com/Linuxbrew/install/issues/56#issuecomment-479698143), where downloading the install script itself did fail, was actually when using a locally built `curl` (v7.58.0, released 2018-01-24) from pkgsrc.

**Comment by sjackman** [comment]
```
Failed during: git fetch origin master:refs/remotes/origin/master --tags --force
```

You could try using `curl` rather than `git`.
`sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)" -- --force-curl`
Note the additional `--` before `--force-curl`. It's important.

https://github.com/Linuxbrew/install/blob/2f519ad489bbdbceb51e6f799a6df5eba9a33ec4/install#L146-L148

**Comment by sjackman** [comment]
Does `git clone --depth=1 https://github.com/Homebrew/brew` work for you?

**Comment by waldyrious** [comment]
> You could try using curl rather than git.
`sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)" -- --force-curl`

That doesn't work for me, I'm afraid:

```
$ sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)" -- --force-curl
ruby: invalid option --force-curl  (-h will show valid options)

$ ruby --version
ruby 1.8.7 (2011-06-30 patchlevel 352) [x86_64-linux]
```

I tried skipping the `--` to see if it made a difference, but it seems to have been ignored:
```
$ sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)" --force-curl
==> This script will install:
/home/waldyrious/.linuxbrew/bin/brew
...SNIP...
==> Downloading and installing Linuxbrew...
error: SSL connect error while accessing https://github.com/Homebrew/brew/info/refs
fatal: HTTP request failed
Failed during: git fetch origin master:refs/remotes/origin/master --tags --force
```

Adding `--force curl` inside the `$(...)` didn't work either, with or without the `--`:
```
$ sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh --force-curl)"
curl: option --force-curl: is unknown
curl: try 'curl --help' or 'curl --manual' for more information
```

```
$ sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh -- --force-curl)"
curl: (6) Couldn't resolve host '--force-curl'
==> This script will install:
/home/waldyrious/.linuxbrew/bin/brew
...SNIP...
==> Downloading and installing Linuxbrew...
error: SSL connect error while accessing https://github.com/Homebrew/brew/info/refs
fatal: HTTP request failed
Failed during: git fetch origin master:refs/remotes/origin/master --tags --force
```

> Does `git clone --depth=1 https://github.com/Homebrew/brew` work for you?

Nope:
```
$ git clone --depth=1 https://github.com/Homebrew/brew
Cloning into 'brew'...
error: SSL connect error while accessing https://github.com/Homebrew/brew/info/refs
fatal: HTTP request failed

$ git --version
git version 1.7.11.4
```

**Comment by waldyrious** [comment]
I'm trying to compile curl from a more recent release branch of pkgsrc to see if it helps.

**Comment by sjackman** [comment]
Try doubling down on the `--`:
`sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)" -- -- --force-curl`

> Nope

You could installing an updated version of `git` as you did for `curl`.

**Comment by waldyrious** [comment]
Compilation of `curl` and `git` is taking a long time and it's getting pretty late here. I'll leave it running and try again tomorrow and report back. Thanks again for all the assistance!

**Comment by waldyrious** [comment]
Ok I now have:

```
$ which git && git --version
~/.pkgsrc/bin/git
git version 2.20.1

$ which curl && curl --version
~/.pkgsrc/bin/curl
curl 7.64.0 ...
```

Doing `sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)" -- -- --force-curl` **does work**: I finally got to the `==> Installation successful` message! :tada:

However :disappointed: the `brew` script itself seems to insist on using the system curl. Trying to run, for example `brew update --force` as recommended by the "successful installation" message results in the following:

```
$ brew vendor-install ruby
==> Downloading https://linuxbrew.bintray.com/bottles-portable-ruby/portable-ruby-2.3.7.x86_64_linux.bottle.tar.gz
curl: (35) SSL connect error
==> Downloading https://github.com/Homebrew/homebrew-portable-ruby/releases/download/2.3.7/portable-ruby-2.3.7.x86_64_linux.bottle.tar.gz

curl: (35) SSL connect error
Error: Failed to download https://linuxbrew.bintray.com/bottles-portable-ruby/portable-ruby-2.3.7.x86_64_linux.bottle.tar.gz and https://github.com/Homebrew/homebrew-portable-ruby/releases/download/2.3.7/portable-ruby-2.3.7.x86_64_linux.bottle.tar.gz!

Do not file an issue on GitHub about this: you will need to figure out for
yourself what issue with your internet connection restricts your access to
both Bintray (used for Homebrew bottles/binary packages) and GitHub
(used for Homebrew updates).

```

However, using [HOMEBREW_NO_ENV_FILTERING=1](https://github.com/Linuxbrew/brew/issues/534#issuecomment-351559415) this works:

```
$ HOMEBREW_NO_ENV_FILTERING=1 brew vendor-install ruby
==> Downloading https://linuxbrew.bintray.com/bottles-portable-ruby/portable-ruby-2.3.7.x86_64_linux.bottle.tar.gz
######################################################################################################################################################################################################################################## 100,0%
==> Pouring portable-ruby-2.3.7.x86_64_linux.bottle.tar.gz
```

So I'm not sure it's fair to say that the installation really succeeded. However, if ensuring that the brew script works properly is beyond the scope of the install script, we can skip that discussion on this issue and focus on this issue's initial goal: ensuring the install script properly handles an old curl version (e.g. by showing an appropriate error message early on). Let me know how I should proceed.

**Comment by sjackman** [comment]
I'm glad to hear that you got the installer working, and found the `HOMEBREW_NO_ENV_FILTERING=1` workaround!

> focus on this issue's initial goal: ensuring the install script properly handles an old curl version (e.g. by showing an appropriate error message early on). Let me know how I should proceed.

A PR to fail early if curl is too old would be great! After that if you have the inclination, you could work on a PR to fix `brew` so that `HOMEBREW_NO_ENV_FILTERING=1` is not needed.

**Comment by waldyrious** [comment]
> A PR to fail early if curl is too old would be great!

Do you happen to know what version (or release date) of curl should be tested for?

> After that if you have the inclination, you could work on a PR to fix `brew` so that `HOMEBREW_NO_ENV_FILTERING=1` is not needed.

I have no idea how I should go about doing that, but if I get some pointers, I could take a stab at it.

**Comment by sjackman** [comment]
> Do you happen to know what version (or release date) of curl should be tested for?

No, I'm afraid I don't. =/ You could try `curl -sS https://github.com >/dev/null` and check the result for `curl: (35) SSL connect error`.
```sh
if [[ $(curl -sS https://github.com 2>&1 >/dev/null) = "curl: (35) SSL connect error" ]]; then
    echo "print a helpful error message 1>&2
    exit 1
fi
```

**Comment by sjackman** [comment]
> I have no idea how I should go about doing that, but if I get some pointers, I could take a stab at it.

I don't have time right this minute, but after we resolve the install issue, I can give you a hand.
