### ISSUE TITLE
linuxbrew getting osx_brew requirements?

### ISSUE THREAD

**Issue by rwheadon** [Linuxbrew/install#58]
I am unsure whether this issue falls under brew or rvm.

After installing linuxbrew and setting rvm to enable autolibs (rvm autolibs homebrew) I am not able to run bundle or gem install commands. The search for requirements seems to be expecting xcode, but since this is linux it isn't there (nor available).

Below is a sample output from the command line:
```
$ rvm reinstall 2.0 --with-openssl-dir=/home/linuxbrew/.linuxbrew/Cellar/openssl/1.0.2r
Checking requirements for osx_brew.
Installing requirements for osx_brew.
Updating system......./
Xcode version older than 4.6.2 installed, download and install newer version from:
.
    http://connect.apple.com
/
After installation open Xcode, go to Downloads and install Command Line Tools.
\
.
Error running 'requirements_osx_brew_update_system ruby-2.0.0-p648',
please read /home/deployer/.rvm/log/1557457671_ruby-2.0.0-p648/update_system.log
Requirements installation failed with status: 1.
```

**Comment by sjackman** [comment]
This sounds to me like a bug in `rvm`. My guess is that `rvm autolibs homebrew` does not currently work with Homebrew on Linux. You could request that feature from the developers of `rvm`.
