### ISSUE TITLE
syntax error, unexpected '.'

### ISSUE THREAD

**Issue by joseph-long** [Linuxbrew/install#65]
Following the instructions from https://docs.brew.sh/Homebrew-on-Linux#install I quickly run into an issue with no clear path forward. I'm on a rather old system (CentOS 6.10 based with ruby 1.8.7), which might have something to do with it.

```
$ sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
-e:178: syntax error, unexpected '.'
    exe if $CHILD_STATUS&.success? && !exe.empty? && Fil...
                          ^
```

**Comment by sjackman** [comment]
@joseph-long Hi, Joseph. Try running…
```sh
HOMEBREW_FORCE_VENDOR_RUBY=1 sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
```

**Comment by sjackman** [comment]
@joehorsnell Is this issue something that you'd be interested in addressing with a PR? This code installs Ruby if it's not found in the `PATH`.
https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh
https://raw.githubusercontent.com/Linuxbrew/install/master/install-ruby
It needs to be modified to check the current version of Ruby, and install the vendored version of Ruby if it's less than 2.3.7.

**Comment by joseph-long** [comment]
Thanks for the tip! I ended up doing an "alternative installation", then figuring out even CentOS `git` was too old... separate issue, though.

**Comment by sjackman** [comment]
Mmm. The plot thickens. It's possible to download a tarball of Homebrew/brew, extract that, and use it to set up an installation of Homebrew on Linux. Something like the following (untested). Better though is to upgrade your distribution of Linux, if possible.
```sh
mkdir -p /home/linuxbrew/.linuxbrew/bin
curl -L https://github.com/Homebrew/brew/archive/2.1.6.tar.gz | tar x -C /home/linuxbrew/.linuxbrew/Homebrew
ln -s ../Homebrew/bin/brew /home/linuxbrew/.linuxbrew/bin
eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
```

**Comment by joseph-long** [comment]
The plot is thick indeed! I opened a new issue over at https://github.com/Homebrew/brew/issues/6274

Unfortunately, I use Linuxbrew to try and save myself from the outdated software on my University's HPC cluster... they won't let me upgrade them to a newer CentOS 🙃
