### ISSUE TITLE
Advice : use shell builtin command first

### ISSUE THREAD

**Issue by leleliu008** [Linuxbrew/install#75]
[https://github.com/Linuxbrew/install/blob/master/install-ruby](url) line 30 `which ruby` replaced by `command -v ruby` is better as `which` is not builtin command in any shell, it may not be pre installed in some os.

**Comment by sjackman** [comment]
https://github.com/Linuxbrew/install/blob/master/install-ruby#L30
Agreed. Would you like to open a PR to change `` `which ruby` `` to `$(command -v ruby)` ?

**Comment by leleliu008** [comment]
@sjackman Yes, I'd like to.
