### ISSUE TITLE
Change the number of jobs in MAKEFLAGS

### ISSUE THREAD

**Issue by tautomer** [Linuxbrew/install#77]
I think the default one is 72 for Linuxbrew, which is wasy too large.

If I run `brew upgrate` or `brew install <formulae>` on the head node of a shared cluster, the whole cluster will get stuck because of this. The only option will be running all brew task on a compute node.

The default for homebrew on Mac is 8. This is a far more rational choice.

Unlike `$HOMEBREW_CC`, there isn't a environmental variable like `HOMEBREW_MAKEFLAGS`. Is it possible to change the flag myself?

**Comment by sjackman** [comment]
The default number of make jobs is the number of CPU threads.
```sh
export HOMEBREW_MAKE_JOBS=8
```
See `man brew` or https://docs.brew.sh/Manpage
